// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (id, name, section)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, name, section, created_at
`

type CreateClassParams struct {
	ID      uuid.UUID
	Name    string
	Section string
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass, arg.ID, arg.Name, arg.Section)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Section,
		&i.CreatedAt,
	)
	return i, err
}

const getAnyClass = `-- name: GetAnyClass :one
SELECT id, name, section, created_at FROM classes LIMIT 1
`

func (q *Queries) GetAnyClass(ctx context.Context) (Class, error) {
	row := q.db.QueryRow(ctx, getAnyClass)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Section,
		&i.CreatedAt,
	)
	return i, err
}
