// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ID        uuid.UUID
	Name      string
	Section   string
	CreatedAt pgtype.Timestamp
}

type Enrollment struct {
	ID         uuid.UUID
	StudentID  uuid.UUID
	ClassID    uuid.UUID
	EnrolledAt pgtype.Timestamp
}

type Faculty struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	FullName    string
	Department  pgtype.Text
	Designation pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type Student struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	FullName    string
	RollNumber  string
	ClassID     uuid.UUID
	DateOfBirth pgtype.Date
	CreatedAt   pgtype.Timestamp
}

type Subject struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type TeachingAssignment struct {
	ID         uuid.UUID
	FacultyID  uuid.UUID
	SubjectID  uuid.UUID
	ClassID    uuid.UUID
	AssignedAt pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	Role      string
}
