// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (id, user_id, full_name, roll_number, class_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (roll_number) DO NOTHING
RETURNING id, user_id, full_name, roll_number, class_id, date_of_birth, created_at
`

type CreateStudentParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FullName   string
	RollNumber string
	ClassID    uuid.UUID
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.RollNumber,
		arg.ClassID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.RollNumber,
		&i.ClassID,
		&i.DateOfBirth,
		&i.CreatedAt,
	)
	return i, err
}
