// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, name)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, created_at
`

type CreateSubjectParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.ID, arg.Name)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
